name: API Tests with Postman

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run Payment Check API Tests
        continue-on-error: true
        run: |
          newman run postman/payment-check-tests.json \
            -e <(echo '${{ secrets.POSTMAN_ENVIRONMENT }}') \
            --reporters cli,html \
            --reporter-html-export payment-check-report.html

      - name: Run Create Invoices API Tests
        continue-on-error: true
        run: |
          newman run postman/create-invoices-tests.json \
            -e <(echo '${{ secrets.POSTMAN_ENVIRONMENT }}') \
            --reporters cli,html \
            --reporter-html-export create-invoices-report.html

      - name: Run Update Invoices API Tests
        continue-on-error: true
        run: |
          newman run postman/update-invoices-tests.json \
            -e <(echo '${{ secrets.POSTMAN_ENVIRONMENT }}') \
            --reporters cli,html \
            --reporter-html-export update-invoices-report.html

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-reports
          path: |
            *.html
          retention-days: 7
